### ISSUE TITLE
Environment file versions

### ISSUE THREAD

**Issue by sivakornchong** [UBC-MDS/mathdistops#7]
Update the environment file with versions

**Comment by sandygross** [comment]
I can do that!

**Comment by carinaya** [comment]
Hi Gross, when I tried to install the env via yaml file, I encounter a problem 
`PackagesNotFoundError: The following packages are not available from current channels:
  - math
  - matplotlib.pyplot
  - scipy.stats`
  
So I search online, the code below with version might be a better way to specify. I paste here for your reference.
```yaml
name: pycounts
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - [other packages you need]
```
